### ISSUE TITLE
Question about "position" and "close"

### ISSUE THREAD

**Issue by flamingo-expert** [brunojkurt/snackfy#1]
Hi. Is there a way to redefine styles? Is it possible to change the position: absolute to the position: fixed and make the closing icon not so small?

**Comment by brunojkurt** [comment]
@flamingo-expert  I will release the next version today or tomorrow and I will add your needs, they are valid and the position property should be already fixed.

**Comment by brunojkurt** [comment]
@flamingo-expert
Now position is fixed and new features released at v1.2.0, I believe that will solve your problem with the closing icon, take a look at the README, you can choose a default icon or pass directly to the snackbar options.
